name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 15 * * *" # UTC 15:00 == JST 00:00 
  workflow_dispatch: # 手動トリガーも可能

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          NAME: ${{ github.repository_owner }}  # 表示名
          BRANCH_NAME: "main"
          UTC_OFFSET: 9           # 日本ならここを 9 にする
          EXCLUDE: ""             # 除外言語（例：java,rust）
          AUTO_PUSH: true
          THEME: ""               # 空欄＝全テーマ生成
          ANIMATION: "load"       # アニメーション（オプション）
          DURATION: 3
          
